import QRCode from "qrcode";
import {
  checkInWindow,
  formatSessionCode,
  sessionCode,
  signCheckInToken,
} from "@/features/checkin/checkin";

// The student's half of check-in: a QR for the counsellor to scan, and the same
// session's short code for when a camera isn't an option.
//
// Server component — the QR is rendered to SVG here, so `qrcode` never reaches
// the client bundle and the signed token is never exposed to client JS.

/**
 * Rendered at a fixed size; the counsellor scans this off the student's screen.
 *
 * Hard-coded ink-on-white, never themed. A QR must stay dark-modules-on-light
 * — plenty of readers won't decode an inverted one — and the spec's quiet zone
 * has to be light too, which is why `margin` is 3 modules and the container
 * below forces a white plate even in dark mode.
 */
async function qrSvg(payload: string): Promise<string> {
  return QRCode.toString(payload, {
    type: "svg",
    errorCorrectionLevel: "M",
    margin: 3,
    width: 132,
    color: { dark: "#241826", light: "#ffffff" },
  });
}

export async function CheckInCode({
  appointmentId,
  studentId,
  appointmentDate,
  startTime,
  endTime,
}: {
  appointmentId: string;
  studentId: string;
  appointmentDate: Date;
  startTime: string;
  endTime: string;
}) {
  const { closes } = checkInWindow({ appointmentDate, startTime, endTime });
  const token = await signCheckInToken({ appointmentId, studentId }, closes);
  const svg = await qrSvg(token);
  const code = formatSessionCode(sessionCode(appointmentId));

  return (
    <div className="mt-4 flex flex-col gap-4 rounded-(--radius-card) bg-surface p-4 sm:flex-row sm:items-center">
      {/* bg-white, not bg-surface: the plate must stay light in dark mode or the
          quiet zone disappears and scanners start failing. */}
      <div
        className="shrink-0 self-center rounded-[8px] bg-white p-1 [&>svg]:block [&>svg]:h-[132px] [&>svg]:w-[132px]"
        // Generated by the qrcode package from our own signed token — no user
        // input reaches this string.
        dangerouslySetInnerHTML={{ __html: svg }}
        aria-hidden
      />
      <div className="min-w-0">
        <h3 className="t-h3">Check in to your session</h3>
        <p className="t-meta mt-1">Show this to your counsellor when you arrive.</p>
        <p className="mt-3 font-mono text-xl font-semibold tracking-[0.12em] text-ink-strong">
          {code}
        </p>
        <p className="t-meta mt-1">
          Can&apos;t scan? Read this code out instead.
        </p>
        <span className="sr-only">
          Your check-in code is {code.split("").join(" ")}. Show the QR code on
          screen to your counsellor, or read this code aloud.
        </span>
      </div>
    </div>
  );
}

/** After the counsellor scans: the code is spent, so it stops being shown. */
export function CheckedInNotice({ checkedInAt }: { checkedInAt: Date }) {
  const time = checkedInAt.toLocaleTimeString("en-IN", {
    hour: "numeric",
    minute: "2-digit",
    timeZone: "UTC",
  });
  return (
    <div className="mt-4 rounded-(--radius-card) bg-surface p-4">
      <p className="text-[0.9375rem] font-semibold text-success-ink">
        Checked in at {time}
      </p>
      <p className="t-meta mt-1">Your counsellor scanned your code.</p>
    </div>
  );
}
